### ISSUE TITLE
Shared Memory between UWP apps.

### ISSUE THREAD

**Issue by Noemata** [StefanWickDev/UWP-FullTrust#1]
We have a rather tricky scenario where we need to share memory between two UWP apps to facilitate extremely high bandwidth data communications (video buffers) between two UWP applications.

For various reasons it's not feasible to do everything in one app.  In the one case we will have a Unity UWP application, and in the other we will have a XAML UWP app.  The Unity 3D app needs to transfer generated textures that are up to 1080P in size to the XAML UWP app for additional processing.

How can this be down?  We are open to any and all possibilities that could facilitate this.  Would it be possible to use a Media Foundation component in some fashion?  Is there anything similar to shared memory DLLs for UWP, even if this requires custom capabilities that would not pass through the store?  Is there some way to leverage AppService to transfer large blocks of data quickly?  Is there a MemoryMapped file option?

We really need some sort of option.  This is going to be running both on a Desktop deployment and the HoloLens.

**Comment by Noemata** [comment]
Even responding with a "too busy" is better than no response at all.  Or better yet, remove the issue section if this is too much of a distraction.

**Comment by StefanWickDev** [comment]
Sorry for the slow response. This repo is a personal spare time project to support my personal blog, not an official Microsoft channel to track feature requests. The best place to post those would be on User Voice: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/
